# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 机场订阅
proxy-providers:
  订阅1:
    url: "机场订阅"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    proxy: 直连

# 节点信息
proxies:
  - { name: 直连, type: direct }

#端口
# port: 7890 # HTTP(S) 代理服务器端口
# socks-port: 7891 # SOCKS5 代理端口
mixed-port: 7890 # HTTP(S) 和 SOCKS 代理混合端口
# redir-port: 7892 # 透明代理端口，用于 Linux 和 MacOS

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

allow-lan: true
bind-address: "*"
# lan-allowed-ips: []
# lan-disallowed-ips: []

# authentication: # http,socks 入口的验证用户名，密码
#   - "username:password"

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict

mode: rule

#自定义 geodata url
geodata-mode: true
geox-url:
  geoip: "https://github.chenc.dev/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db"
  geosite: "https://github.chenc.dev/github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db"

geo-auto-update: false # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时

log-level: info
ipv6: true

unified-delay: true # 统一延迟，去除握手延迟
tcp-concurrent: true # TCP 并发连接所有 IP, 将使用最快握手的 TCP

# 控制面板
external-controller: 0.0.0.0:9090
secret: "passwd"
# Mihomo Docker
external-ui: "/root/.config/mihomo/ui"
external-ui-name: zashboard
external-ui-url: "https://github.chenc.dev/github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# interface-name: en0 # 设置出口网卡
# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
# 可选： "chrome","firefox","safari","ios","random","none" options.
client-fingerprint: chrome

keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true # 持久化 fake-ip

# 入站
tun:
  enable: false
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-detect-interface: true # 自动识别出口网卡
  auto-route: true # 配置路由表
  auto-redirect: true # 自动配置 iptables 以重定向 TCP 连接。仅支持 Linux。
  strict-route: true

# 嗅探
sniffer:
  enable: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"
    - "Mijia Cloud"
    - "+.push.apple.com"

# DNS模块
dns:
  enable: true
  cache-algorithm: arc
  # 配置后面的nameserver、fallback和nameserver-policy向dns服务器的连接过程是否遵守遵守rules规则
  # 如果为false（默认值）则这三部分的dns服务器在未特别指定的情况下会直连
  # 如果为true，将会按照rules的规则匹配链接方式（走代理或直连），如果有特别指定则任然以指定值为准
  # 仅当proxy-server-nameserver非空时可以开启此选项, 强烈不建议和prefer-h3一起使用
  # 此外，这三者配置中的dns服务器如果出现域名会采用default-nameserver配置项解析，也请确保正确配置default-nameserver
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: blacklist
  # 配置不使用 fake-ip 的域名
  fake-ip-filter:
    - "rule-set:private_domain"
    - "rule-set:cn_domain"
    - "rule-set:fakeipfilter_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"

  # 用于解析 nameserver，fallback 以及其他 DNS 服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
    - https://223.5.5.5/dns-query
    - 223.5.5.5
    - 114.114.114.114
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853

  # 专用于节点域名解析的 DNS 服务器，非必要配置项，如果不填则遵循nameserver-policy、nameserver和fallback的配置
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - system
  nameserver:
    - https://8.8.8.8/dns-query#RULES&ecs=223.5.5.0/24
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114

# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
# 注意锚点必须放在引用的上方，可以集中把锚点全部放yaml的顶部。
pr:
  &pr {
    type: select,
    proxies:
      [
        🚀 默认代理,
        🍀 省流节点,
        🔯 香港故转,
        🔯 日本故转,
        ♻️ 香港自动,
        ♻️ 日本自动,
        ♻️ 美国自动,
        ♻️ 韩国自动,
        ♻️ 新加坡自动,
        ♻️ 自动选择,
        🇭🇰 香港节点,
        🇯🇵 日本节点,
        🇺🇲 美国节点,
        🇰🇷 韩国节点,
        🇸🇬 新加坡节点,
        🌐 全部节点,
        直连
      ]
  }
proxy-groups:
  - {
      name: 🚀 默认代理,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🍀 省流节点,
          🔯 日本故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 美国自动,
          ♻️ 韩国自动,
          ♻️ 新加坡自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇺🇲 美国节点,
          🇰🇷 韩国节点,
          🇸🇬 新加坡节点,
          🌐 全部节点,
          直连
        ]
    }
  - { name: 🌐 全部节点, type: select, include-all: true }
  - {
      name: 🍀 省流节点,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "0.1|0.01"
    }
  - {
      name: 🇭🇰 香港节点,
      type: select,
      include-all: true,
      filter: "(?i)港|澳|台|hk|hongkong|hong kong"
    }
  - {
      name: 🇯🇵 日本节点,
      type: select,
      include-all: true,
      filter: "(?i)日|jp|japan"
    }
  - {
      name: 🇺🇲 美国节点,
      type: select,
      include-all: true,
      filter: "(?i)美|us|unitedstates|united states"
    }
  - {
      name: 🇰🇷 韩国节点,
      type: select,
      include-all: true,
      filter: "(?i)韩|kr|korea|southkorea|south korea"
    }
  - {
      name: 🇸🇬 新加坡节点,
      type: select,
      include-all: true,
      filter: "(?i)新|sg|singapore"
    }

  - { name: 📹 YouTube, <<: *pr }
  - { name: 🌸 Google, <<: *pr }
  - { name: 🤖 ChatGPT, <<: *pr }
  - { name: 👨🏿‍💻 GitHub, <<: *pr }
  - { name: 🐬 OneDrive, <<: *pr }
  - { name: 🪟 Microsoft, <<: *pr }
  - { name: 📲 Telegram, <<: *pr }
  - { name: 🎯 直连, type: select, proxies: [直连, 🚀 默认代理] }
  - { name: 🐟 漏网之鱼, <<: *pr }
  - {
      name: ♻️ 自动选择,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      exclude-filter: "直连"
    }
  - {
      name: ♻️ 香港自动,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)港|澳|台|hk|hong",
      exclude-filter: "日|韩|新|深|美"
    }
  - {
      name: ♻️ 日本自动,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)日|jp|japan",
      exclude-filter: "港|台|韩|新|美"
    }
  - {
      name: ♻️ 美国自动,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)美|us|states|america",
      exclude-filter: "港|台|日|韩|新"
    }
  - {
      name: ♻️ 韩国自动,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)韩|kr|korea|southkorea|south korea"
    }
  - {
      name: ♻️ 新加坡自动,
      type: url-test,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)新|sg|singapore"
    }

  - {
      name: 🔯 香港故转,
      type: fallback,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)港|hk|hong",
      exclude-filter: "台|日|韩|新|深|美"
    }
  - {
      name: 🔯 日本故转,
      type: fallback,
      include-all: true,
      url: https://www.gstatic.com/generate_204,
      tolerance: 20,
      interval: 300,
      filter: "(?i)日|jp|japan",
      exclude-filter: "港|台|韩|新|美"
    }

###########################################################
##############图标网站 https://emojiterra.com ##############
###########################################################

# 规则匹配
# 此规则部分没有做防泄露处理，因为弊严重大于利！
rules:
  # 本地局域网
  - RULE-SET,private_ip,🎯 直连,no-resolve
  - RULE-SET,private_domain,🎯 直连

  #ai中转分流代理
  - DOMAIN,new.sharedchat.cc,🎯 直连
  - DOMAIN-SUFFIX,animon.ai,🤖 ChatGPT
  - DOMAIN-SUFFIX,nebius.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,x666.me,🤖 ChatGPT
  - DOMAIN-SUFFIX,ai-wave.org,🤖 ChatGPT
  - DOMAIN,ai.hybgzs.com,🎯 直连

  # 自定义过滤
  - DOMAIN,github.chenc.dev,🎯 直连
  - DOMAIN,pro.258899.xyz,🎯 直连
  - DOMAIN-SUFFIX,hf.space,♻️ 香港自动
  - DOMAIN-SUFFIX,yandex.com,♻️ 美国自动
  - DOMAIN-SUFFIX,yandex.net,♻️ 美国自动
  - DOMAIN-SUFFIX,googleapis.cn,🌸 Google # google play store 规则
  - DOMAIN,gh.258899.xyz,🎯 直连
  - DOMAIN-SUFFIX,gh-proxy.com,🎯 直连
  - DOMAIN-SUFFIX,cnb.cool,🎯 直连

    # 直连规则
  - RULE-SET,cn_ip,🎯 直连,no-resolve
  - RULE-SET,cn_domain,🎯 直连
  - GEOSITE,cn,🎯 直连
  - GEOIP,CN,🎯 直连

  # 默认代理
  - RULE-SET,ai,🤖 ChatGPT

  - RULE-SET,github_domain,👨🏿‍💻 GitHub
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google_domain,🌸 Google
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🪟 Microsoft
  - RULE-SET,apple_domain,🎯 直连
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET,apple_ip,🎯 直连
  - RULE-SET,google_ip,🌸 Google,no-resolve
  - RULE-SET,telegram_ip,📲 Telegram,no-resolve
  - RULE-SET,gfw_domain,🚀 默认代理
  - RULE-SET,geolocation-!cn,🚀 默认代理

  - MATCH,🐟 漏网之鱼

# 规则集
rule-anchor:
  ip: &ip { type: http, interval: 86400, behavior: ipcidr, format: mrs }
  domain: &domain { type: http, interval: 86400, behavior: domain, format: mrs }
  class:
    &class { type: http, interval: 86400, behavior: classical, format: text }
rule-providers:
  fakeipfilter_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"
    }
  private_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
    }
  ai:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs"
    }
  youtube_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
    }
  google_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
    }
  github_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"
    }
  telegram_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"
    }
  onedrive_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"
    }
  microsoft_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"
    }
  apple_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"
    }
  gfw_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"
    }
  geolocation-!cn:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"
    }
  cn_domain:
    {
      <<: *domain,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
    }

  private_ip:
    {
      <<: *ip,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
    }
  cn_ip:
    {
      <<: *ip,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
    }
  google_ip:
    {
      <<: *ip,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"
    }
  telegram_ip:
    {
      <<: *ip,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
    }
  apple_ip:
    {
      <<: *ip,
      url: "https://github.chenc.dev/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"
    }
